simu:
  picFile: electrostatic_plasma2D.h5
  nDim: 2

sample:
  iEnd: 600
  step: 1

data:
  dataClass: pic
  outType: solution
  outScaling: 1
  space_dim: 2
  xStep: 1
  yStep: 1
  zStep: 1
  seed: null
  dataFile: fno_data/PIC2D_electrostatic.h5
  trainRatio: 0.8
  batchSize:  8        # Global Batch size 
  sampling_mode: None  # [fixed, ordered, random]
 

model:
  da: 3
  du: 2
  dv: 32
  kX: 16
  kY: 16
  kZ: None
  n_dims: 2
  n_layers: 4
  bias: false
  non_linearity: gelu
  scaling_layers: 2
  use_postfnochannel_mlp: false
  channel_mlp_expansion: 4
  use_skip_connection: false
  skip_type: soft-gating
  use_dse: false                        # Direct Spectral Evaluation
  use_kb: true                          # Kaiser-Bessel NUFFT
  use_toeplitz: false                   # Toeplitz NUFFT


optim:
  name: adam
  lr: 1.0e-3
  weight_decay: 1.0e-5

lr_scheduler:
  # scheduler: CosAnnealingLR
  # T_max: 50000
  scheduler: StepLR
  step_size: 50.0
  gamma: 0.5

loss:
  name: L1Loss
  # absolute: false
  
parallel_strategy:
  ddp: false                  # Distributed Data Parallel
  gpus_per_node: 4

train:
  trainDir: PIC2D
  epochs: 5                     # nEpochs
  checkpoint: None
  saveInterval: 5
  disableTensorboard: true

eval:
  runId: 1
  imgExt: png
  evalDir: eval2D
  dim: 2
  kc : 0.5
  NG : 32
  T: 5
  dt: 0.05
  Vt: 1
  nParticle: 50
  Qm : -1
  alpha: 0.01
  
profile:
  enableProfiler: false
  profiler: nsys
  profileDir: nsysProf
  evalOnly: false
  input_shape: [1,3,10000]   # relevant only if evalOnly=true or compile_eval=true
  use_amp: 0
  use_complex_amp: 0
  benchmark: true
  niter: 5
  compile_eval: 0       
  compile_train: 0
  compile_mode: default    # compiler mode 
 