simu:
  dataDir: simuData
  nDim: 2
  Rayleigh: 1e7
  resFactor: 1
  seed: 12345
  dtSimu: 0.001
  tEnd: 100
  tInit: 50
  nSimu: 1
  dtData: 0.001
  
sample:
  inSize: 1
  outStep: 1
  inStep: 500

data:
  outType: update
  outScaling: 1000
  space_dim: 2
  xStep: 1
  yStep: 1
  zStep: 1
  seed: null
  dataFile: dataset_256x64_Ra1e7_dt1e-3_update.h5
  trainRatio: 0.8
  batchSize: 20
  sampling_mode: None  # [fixed, ordered, random]
  pad_to_fullGrid: false
  use_fixedPatch_startIdx: false
  nPatch_per_sample: 1
  use_minLimit: false
  padding : [0,0,0,0]
  add_fullGrid: false
  # slices: 
  # patch_startIdx: 

model:
  da: 4
  du: 4
  dv: 16
  kX: 12
  kY: 12
  kZ: None
  n_dims: 2
  n_layers: 2
  bias: false
  non_linearity: gelu
  scaling_layers: 4
  use_prechannel_mlp: true
  use_postfnochannel_mlp: false
  channel_mlp_expansion: 4
  use_skip_connection: false
  skip_type: soft-gating
  use_dse: false
  get_subdomain_output: false             # set to true only for inference
  iXBeg: 0
  iYBeg: 0
  iXEnd: 256
  iYEnd: 32

optim:
  name: adam
  lr: 1.0e-4
  weight_decay: 1.0e-5

lr_scheduler:
  scheduler: CosAnnealingLR
  T_max: 50000
  # scheduler: StepLR
  # step_size: 100.0
  # gamma: 0.98

loss:
  name: VectorNormLoss
  absolute: false
  
parallel_strategy:
  ddp: false    # Distributed Data Parallel
  gpus_per_node: 4

train:
  trainDir: trainDir
  epochs: 10
  checkpoint: None
  saveInterval: 5
  disableTensorboard: false

eval:
  iSimu: 0
  runId: 1
  imgExt: pdf
  evalDir: eval
  tSteps: 1
  model_dt: 1e-3
 