simu:
  dataDir: pysdc_fno/rbc3d_1e-5_pysdc
  Rayleigh: 1e5
  Pr: 0.7
  resFactor: 32   # z-axis
  nDim: 3
  dtSimu: [6e-2, 4e-2, 2e-2, 1e-2, 5e-3, 2e-3]
  iBeg: 100
  nSimu: 6
  dtData: 0.5

  
sample:
  inSize: 1      # number of input fields
  outStep: 1     # iOutField = iField + outstep
  inStep: 1      # slice interval

data:
  dataClass: rbc
  outType: solution
  outScaling: 1
  space_dim: 3
  xStep: 1
  yStep: 1
  zStep: 1
  dataFile: fno_data/RBC3D_64x64x32_Ra1e5_dt0_5_solution.h5
  batchSize: 20        # Global Batch size
  sampling_mode: None  # Domain Sampling: [fixed, ordered, random]
  pad_to_fullGrid: false
  use_fixedPatch_startIdx: false
  nPatch_per_sample: 1
  use_minLimit: false
  padding : [0,0,0,0]
  add_fullGrid: false
  # slices: 
  # patch_startIdx: 

model:
  da: 5
  du: 5
  dv: 25
  kX: 12
  kY: 12
  kZ: 6
  n_dims: 3
  n_layers: 2
  bias: false
  non_linearity: gelu
  scaling_layers: 4
  use_postfnochannel_mlp: false
  channel_mlp_expansion: 4
  use_skip_connection: false
  skip_type: soft-gating
  use_dse: false
  get_subdomain_output: false             # set to true only for inference
  iXBeg: 0
  iYBeg: 0
  iZBeg: 0
  iXEnd: 64
  iYEnd: 64
  iZEnd: 32

optim:
  name: adam
  lr: 1.0e-4
  weight_decay: 1.0e-5

lr_scheduler:
  scheduler: CosAnnealingLR
  T_max: 50000
  # scheduler: StepLR
  # step_size: 100.0
  # gamma: 0.98

loss:
  name: VectorNormLoss
  absolute: false
  
parallel_strategy:
  ddp: false                       # Distributed Data Parallel
  gpus_per_node: 4

train:
  trainDir: RBC3D
  epochs: 5                     # nEpochs
  checkpoint: None
  saveInterval: 5
  disableTensorboard: true

eval:
  nSamples: 100
  runId: 1
  imgExt: png
  evalDir: eval3D
  tSteps: 1
  model_dt: 0.5
  subtitle: "(64,64,32)"

profile:
  enableProfiler: false
  profiler: nsys
  profileDir: nsysProf
  evalOnly: false
  input_shape: [1,5,256,256,64]   # relevant only if evalOnly=true or compile_eval=true
  use_amp: 0
  benchmark: true
  compile_eval: 0      
  compile_train: 0
  compile_mode: default    # compiler mode 
 